source 'git@git.pixio.com:pixio-libraries/specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'PXBlockAlertView', :exclusive => true do
  pod "PXBlockAlertView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "PXBlockAlertView", :path => "../"

  
end
