source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'PXBlockAlertView' do
  pod "PXBlockAlertView", :path => "../"
end

target 'Tests' do
  pod "PXBlockAlertView", :path => "../"

  
end
